#lang info
(define collection "bdnd")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib" "typed-racket-lib"))
(define scribblings '(("scribblings/bdnd.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(hin))
(define license '(Apache-2.0 OR MIT))
(define raco-commands '(("bdnd" (submod bdnd main) "compress a directory to a single module" #f)))
